### ISSUE TITLE
Rename to bem-loader

### ISSUE THREAD

**Issue by awinogradov** [bem/webpack-bem-loader#3]
So, I can republish (bem-loader)[https://www.npmjs.com/package/bem-loader] with the different name, and we'll use `bem-loader`.`bem` option in webpack.config instead `bemLoader` and `bem` in the list of loaders instead of `webpack-bem`.

**Comment by Yeti-or** [comment]
but right now this loader is almost only for `bem-react`

**Comment by awinogradov** [comment]
Definitely, no. It's for loading declaration and css for bem-entities. It's no about react in fact.

**Comment by Yeti-or** [comment]
okay not about react, but for loading declaraition we have no standart:
right now we have only one implementation: `applyDecls`, and it's working only in `bem-react-core`

**Comment by awinogradov** [comment]
What about `decls-loader`? 

cc @veged @dfilatov

**Comment by dfilatov** [comment]
I don't quite undestand what the problem is, especially:
> bem option in webpack.config instead bemLoader and bem in the list of loaders instead of webpack-bem

**Comment by awinogradov** [comment]
No problem with this option actually, because webpack2 hasn't this field and every loader should pass params by `options` field in the array of loaders near `test`, `include` and etc. This conversation about loader name. @Yeti-or want rename it to `bem-react`. I suggested `bem-loader`. Now its name is `webpack-bem-loader`.

**Comment by veged** [comment]
maybe just drop this question? ;-) cause with webpack2 it will be irrelevant

**Comment by awinogradov** [comment]
Yes, current loaders don't need name with special prefix
