### ISSUE TITLE
Зачем нужен новый лоадер, если есть BEMPAK?

### ISSUE THREAD

**Issue by yar-usenko** [bem/webpack-bem-loader#4]
Зачем начали разработку нового лоадера, если есть [bempack](https://github.com/bempack)?
Может лучше его довести до ума?

**Comment by awinogradov** [comment]
@yar-usenko потому что это плагин специально для [bem-react-core](//github.com/bem/bem-react-core). Загляни внутрь и ты увидишь, что он работает с кастомным синтаксисом импортов.

**Comment by yar-usenko** [comment]
Спасибо за ответ)
Может лучше тогда переназвать его bem-react-core-loader, чтоб такие как я не недоумивали?)

**Comment by awinogradov** [comment]
Я думаю все решится наличием readme
